Auth0.setClient({
    "id": "FoUYTXQQwQPt9jHvlQgMiLzQg60NKFNW",
    "tenant": "logrocket",
    "subscription": "enterprise",
    "authorize": "https://logrocket.auth0.com/authorize",
    "callback": "https://app.logrocket.com",
    "hasAllowedOrigins": true,
    "strategies": [{
        "name": "auth0",
        "connections": [{
            "name": "Username-Password-Authentication",
            "passwordPolicy": "fair",
            "showSignup": true,
            "showForgot": true
        }]
    }, {
        "name": "github",
        "connections": [{
            "name": "github",
            "scope": ["user:email"]
        }]
    }, {
        "name": "google-oauth2",
        "connections": [{
            "name": "google-oauth2",
            "scope": ["email", "profile"]
        }]
    }, {
        "name": "oidc",
        "connections": [{
            "name": "zhszok",
            "display_name": "American Safety Council",
            "domain": "amersc.com",
            "domain_aliases": ["amersc.com"],
            "scope": "openid profile"
        }]
    }, {
        "name": "samlp",
        "connections": [{
            "name": "ally",
            "domain": "ally.com",
            "domain_aliases": ["ally.com", "invest.ally.com"]
        }, {
            "name": "y5nros",
            "domain": "e-farmcredit.com",
            "domain_aliases": ["e-farmcredit.com", "rural1st.com"]
        }, {
            "name": "lc9zlj",
            "display_name": "SAML",
            "domain": "brex.com",
            "domain_aliases": ["brex.com", "brex-external.com"]
        }, {
            "name": "cogito-corp",
            "domain": "cogitocorp.com",
            "domain_aliases": ["cogitocorp.com"]
        }, {
            "name": "ajjaii",
            "display_name": "smartbnb",
            "domain": "smartbnb.io",
            "domain_aliases": ["smartbnb.io"]
        }, {
            "name": "om",
            "domain": "ormutual.com",
            "domain_aliases": ["ormutual.com"]
        }, {
            "name": "fbfaae",
            "domain": "elevate.com",
            "domain_aliases": ["elevate.com"]
        }, {
            "name": "lljtyc",
            "domain": "nipr.com",
            "domain_aliases": ["nipr.com", "naic.org"]
        }, {
            "name": "m1aep7",
            "domain": "assignar.com",
            "domain_aliases": ["assignar.com"]
        }, {
            "name": "vco3yj",
            "domain": "mantl.com",
            "domain_aliases": ["mantl.com"]
        }, {
            "name": "o1n3rt",
            "domain": "lfg.com",
            "domain_aliases": ["lfg.com"]
        }, {
            "name": "vhqkrc",
            "domain": "gong.io",
            "domain_aliases": ["gong.io"]
        }, {
            "name": "alaigh",
            "domain": "bjs.com",
            "domain_aliases": ["bjs.com"]
        }, {
            "name": "mj7uvx",
            "domain_aliases": ["rbi.com"]
        }, {
            "name": "3hq1bs",
            "domain": "md.ca",
            "domain_aliases": ["md.ca"]
        }, {
            "name": "onstqn",
            "domain_aliases": ["rippling.com"]
        }, {
            "name": "b2a9mh",
            "domain_aliases": ["kambi.com"]
        }, {
            "name": "discover",
            "domain_aliases": ["discover.com"]
        }, {
            "name": "ckdeut",
            "domain": "ipaper.com",
            "domain_aliases": ["ipaper.com"]
        }, {
            "name": "wfco7k",
            "domain": "cisco.com",
            "domain_aliases": ["cisco.com"]
        }, {
            "name": "nccnr2",
            "domain": "assurance.com",
            "domain_aliases": ["assurance.com"]
        }, {
            "name": "gyxjms",
            "domain": "beachbody.com",
            "domain_aliases": ["beachbody.com"]
        }, {
            "name": "rttohs",
            "domain": "cpa.texas.gov",
            "domain_aliases": ["cpa.texas.gov"]
        }, {
            "name": "ud6cop",
            "domain": "talkdesk.com",
            "domain_aliases": ["talkdesk.com"]
        }, {
            "name": "7vojs5",
            "domain": "ramp.com",
            "domain_aliases": ["ramp.com"]
        }, {
            "name": "cr8lym",
            "domain": "trinet.com",
            "domain_aliases": ["trinet.com", "mimportal.trinet.com"]
        }, {
            "name": "acns5j",
            "domain": "auctane.com",
            "domain_aliases": ["auctane.com"]
        }, {
            "name": "kdbcu0",
            "domain": "willowsofwinter.com",
            "domain_aliases": ["willowsofwinter.com"]
        }, {
            "name": "inu0wd",
            "domain": "oncolens.com",
            "domain_aliases": ["oncolens.com"]
        }, {
            "name": "830rie",
            "domain": "xyleme.com",
            "domain_aliases": ["xyleme.com"]
        }, {
            "name": "rgjofh",
            "domain": "illumio.com",
            "domain_aliases": ["illumio.com"]
        }, {
            "name": "yl7xpo",
            "domain": "bwater.com",
            "domain_aliases": ["bwater.com"]
        }, {
            "name": "3qixyg",
            "domain": "nandos.co.uk",
            "domain_aliases": ["nandos.co.uk"]
        }, {
            "name": "ld6cqy",
            "domain": "1010data.com",
            "domain_aliases": ["1010data.com"]
        }, {
            "name": "tnoxf1",
            "domain": "blizzard.com",
            "domain_aliases": ["blizzard.com"]
        }, {
            "name": "li6gxc",
            "domain": "swagup.com",
            "domain_aliases": ["swagup.com"]
        }, {
            "name": "mgxe1z",
            "domain": "hightoweradvisors.com",
            "domain_aliases": ["hightoweradvisors.com"]
        }, {
            "name": "qszjbt",
            "domain": "cdk.com",
            "domain_aliases": ["cdk.com"]
        }, {
            "name": "orthodox-union",
            "domain": "ou.org",
            "domain_aliases": ["ou.org"]
        }, {
            "name": "visions-fcu",
            "domain": "visionsfcu.org",
            "domain_aliases": ["visionsfcu.org"]
        }, {
            "name": "4rixnt",
            "domain": "sunrider.com",
            "domain_aliases": ["sunrider.com"]
        }, {
            "name": "umr1po",
            "domain": "tevera.com",
            "domain_aliases": ["tevera.com"]
        }, {
            "name": "fpcbbf",
            "domain": "magmutual.com",
            "domain_aliases": ["magmutual.com"]
        }, {
            "name": "gxjf7g",
            "domain": "revv-up.com",
            "domain_aliases": ["revv-up.com"]
        }, {
            "name": "rsdujo",
            "domain": "science37.com",
            "domain_aliases": ["science37.com"]
        }, {
            "name": "660vtf",
            "domain": "tempus.com",
            "domain_aliases": ["tempus.com"]
        }, {
            "name": "fehiuk",
            "domain": "supernovacompanies.com",
            "domain_aliases": ["supernovacompanies.com", "supernovatech.com"]
        }, {
            "name": "idevxe",
            "domain": "healthpilot.com",
            "domain_aliases": ["healthpilot.com"]
        }, {
            "name": "zg2tcu",
            "domain": "dutchie.com",
            "domain_aliases": ["dutchie.com"]
        }, {
            "name": "ln0h7g",
            "domain": "familypromise.org",
            "domain_aliases": ["familypromise.org"]
        }, {
            "name": "d4ncti",
            "domain": "healthcatalyst.com",
            "domain_aliases": ["healthcatalyst.com"]
        }, {
            "name": "zf7i6v",
            "domain": "hq.bill.com",
            "domain_aliases": ["hq.bill.com"]
        }, {
            "name": "mb6w3n",
            "domain": "truework.com",
            "domain_aliases": ["truework.com"]
        }, {
            "name": "xpxthk",
            "domain": "thredup.com",
            "domain_aliases": ["thredup.com"]
        }, {
            "name": "ufus9j",
            "domain": "ipipeline.com",
            "domain_aliases": ["ipipeline.com"]
        }, {
            "name": "rldyoz",
            "domain": "balanceinnovations.com",
            "domain_aliases": ["balanceinnovations.com"]
        }, {
            "name": "nvpfw1",
            "domain": "optimize.health",
            "domain_aliases": ["optimize.health"]
        }, {
            "name": "dfxx73",
            "domain": "realpage.com",
            "domain_aliases": ["realpage.com"]
        }, {
            "name": "tnu1el",
            "domain": "vanco.com",
            "domain_aliases": ["vanco.com"]
        }, {
            "name": "gqqpcf",
            "domain": "wheniwork.com",
            "domain_aliases": ["wheniwork.com"]
        }, {
            "name": "nugpmu",
            "domain": "testrippling.com",
            "domain_aliases": ["testrippling.com"]
        }, {
            "name": "6e4z4s",
            "domain": "coactionspecialty.com",
            "domain_aliases": ["coactionspecialty.com"]
        }, {
            "name": "qw1tps",
            "domain": "lev.co",
            "domain_aliases": ["lev.co"]
        }, {
            "name": "dtkfxo",
            "domain": "sema4.com",
            "domain_aliases": ["sema4.com"]
        }, {
            "name": "4gfrvn",
            "domain": "canopy.security",
            "domain_aliases": ["canopy.security"]
        }, {
            "name": "bestow",
            "domain": "bestow.com",
            "domain_aliases": ["bestow.com"]
        }, {
            "name": "yhhieu",
            "domain": "bdc.ca",
            "domain_aliases": ["bdc.ca"]
        }, {
            "name": "ozrul3",
            "domain": "appfire.com",
            "domain_aliases": ["appfire.com"]
        }, {
            "name": "owy4gn",
            "domain": "voya.com",
            "domain_aliases": ["voya.com"]
        }, {
            "name": "kndzl4",
            "domain": "arivo.com",
            "domain_aliases": ["arivo.com"]
        }, {
            "name": "1sz4y0",
            "domain": "riamoneytransfer.com",
            "domain_aliases": ["riamoneytransfer.com"]
        }, {
            "name": "tdz4c3",
            "domain": "wasabi.com",
            "domain_aliases": ["wasabi.com"]
        }, {
            "name": "2pwtgi",
            "domain": "7-11.com",
            "domain_aliases": ["7-11.com"]
        }, {
            "name": "paymentsense",
            "domain": "dojo.tech",
            "domain_aliases": ["dojo.tech"]
        }, {
            "name": "i5yh1h",
            "domain": "virtualvaults.com",
            "domain_aliases": ["virtualvaults.com"]
        }, {
            "name": "urvlvv",
            "domain": "coxautoinc.com",
            "domain_aliases": ["coxautoinc.com"]
        }, {
            "name": "hha9du",
            "domain": "pointfive.co",
            "domain_aliases": ["pointfive.co"]
        }, {
            "name": "costar-group",
            "domain": "costar.com",
            "domain_aliases": ["costar.com"]
        }, {
            "name": "modernloop",
            "domain": "modernloop.io",
            "domain_aliases": ["modernloop.io"]
        }, {
            "name": "vbapfp",
            "domain": "nomadhealth.com",
            "domain_aliases": ["nomadhealth.com"]
        }, {
            "name": "5xdwzh",
            "domain": "reddit.com",
            "domain_aliases": ["reddit.com"]
        }, {
            "name": "cpchem",
            "domain": "cpchem.com",
            "domain_aliases": ["cpchem.com"]
        }, {
            "name": "3gk3ju",
            "domain": "ourfamilywizard.com",
            "domain_aliases": ["ourfamilywizard.com"]
        }, {
            "name": "q2urql",
            "domain": "kynetec.com",
            "domain_aliases": ["kynetec.com"]
        }, {
            "name": "akwp12",
            "domain": "drift.com",
            "domain_aliases": ["drift.com"]
        }, {
            "name": "costar-str",
            "domain": "costar.com",
            "domain_aliases": ["costar.com"]
        }, {
            "name": "costar-suite",
            "domain": "costar.com",
            "domain_aliases": ["costar.com"]
        }, {
            "name": "bxlzhx",
            "domain": "riversideinsights.com",
            "domain_aliases": ["riversideinsights.com"]
        }, {
            "name": "hpzc7g",
            "domain": "iterable.com",
            "domain_aliases": ["iterable.com"]
        }, {
            "name": "mbeqdw",
            "domain": "fxreplay.com",
            "domain_aliases": ["fxreplay.com"]
        }, {
            "name": "9j6o7u",
            "domain": "teletracking.com",
            "domain_aliases": ["teletracking.com"]
        }, {
            "name": "s9wv28",
            "domain": "6sense.com",
            "domain_aliases": ["6sense.com"]
        }, {
            "name": "zoll-data",
            "domain": "zoll.com",
            "domain_aliases": ["zoll.com"]
        }, {
            "name": "dtizdl",
            "domain": "zywave.com",
            "domain_aliases": ["zywave.com"]
        }, {
            "name": "nvgobd",
            "domain": "obviohealth.com",
            "domain_aliases": ["obviohealth.com"]
        }, {
            "name": "lnnsvoe"
        }, {
            "name": "zpi9s0",
            "domain": "ec.ai",
            "domain_aliases": ["ec.ai"]
        }, {
            "name": "a95o98",
            "domain": "coxautoinc.com",
            "domain_aliases": ["coxautoinc.com"]
        }, {
            "name": "6kzyyo",
            "domain": "verizon.com",
            "domain_aliases": ["verizon.com"]
        }, {
            "name": "autd9h",
            "domain": "mckesson.com",
            "domain_aliases": ["mckesson.com", "mckesson.ca"]
        }, {
            "name": "i1xsad",
            "domain": "parmonic.com",
            "domain_aliases": ["parmonic.com"]
        }, {
            "name": "mwoavh",
            "domain": "valentino.com",
            "domain_aliases": ["valentino.com", "spindox.it"]
        }, {
            "name": "oyyuhw",
            "domain": "collectivedata.com",
            "domain_aliases": ["collectivedata.com"]
        }, {
            "name": "n7ebxo",
            "domain": "classpass.com",
            "domain_aliases": ["classpass.com", "mindbodyonline.com"]
        }, {
            "name": "sbxdj5",
            "domain": "gozego.com",
            "domain_aliases": ["gozego.com"]
        }, {
            "name": "rcdveh",
            "domain": "mmascend.com",
            "domain_aliases": ["mmascend.com"]
        }, {
            "name": "p66lr4",
            "domain": "permiso.io",
            "domain_aliases": ["permiso.io"]
        }, {
            "name": "4qnlje",
            "domain": "phaidra.ai",
            "domain_aliases": ["phaidra.ai"]
        }, {
            "name": "3lnuxy",
            "domain": "fabuwood.com",
            "domain_aliases": ["fabuwood.com"]
        }, {
            "name": "6vmxfr"
        }, {
            "name": "1iuyxb",
            "domain": "roofstock.com",
            "domain_aliases": ["roofstock.com"]
        }, {
            "name": "z5i4l8",
            "domain": "akidolabs.com",
            "domain_aliases": ["akidolabs.com", "corp.akidolabs.com"]
        }, {
            "name": "v4ndkb",
            "domain": "usfoods.com",
            "domain_aliases": ["usfoods.com"]
        }, {
            "name": "dm0nxq",
            "domain": "safetyculture.io",
            "domain_aliases": ["safetyculture.io"]
        }, {
            "name": "ue7nfs",
            "domain": "zefr.com",
            "domain_aliases": ["zefr.com"]
        }, {
            "name": "dvvt5q",
            "domain": "lumificyber.com",
            "domain_aliases": ["lumificyber.com"]
        }, {
            "name": "4z2qn4",
            "domain": "easypost.com",
            "domain_aliases": ["easypost.com"]
        }, {
            "name": "kl3fdz",
            "domain": "semperis.com",
            "domain_aliases": ["semperis.com"]
        }]
    }, {
        "name": "windowslive",
        "connections": [{
            "name": "windowslive",
            "scope": ["https://graph.microsoft.com/User.Read"]
        }]
    }]
});